# Generated by Django 3.1.6 on 2021-02-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiorecord',
            old_name='data',
            new_name='date',
        ),
    ]
