# Generated by Django 3.1.6 on 2021-02-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210206_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyboardRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('state', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MouseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('state', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WindowRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('state', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
