# Generated by Django 3.1.6 on 2021-02-16 03:08

from django.db import migrations, models
import os

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
